export default Object.freeze({
    ID: 'IDENTIFIER',
    NUM: 'NUMBER',
    PLUS: '+',
    MINUS: '-',
    STAR: '*',
    SLASH: '/',
    CARET: '^',
    BANG: '!',
    EQ: '=',
    EE: '==',
    NE: '!=',
    GT: '>',
    GE: '>=',
    LT: '<',
    LE: '<=',
    OR: '||',
    AND: '&&',
    LPR: '(',
    RPR: ')',
    NULLCHAR: '\0',
})
